/** TypeORM */
import { Entity } from 'typeorm';
import {
  Column,
  CreateDateColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from 'typeorm';

/** Entities */
import { Topic } from './Topic';
import { User } from './User';

/** Class validator */
import { Length } from 'class-validator';

@Entity()
export class Post {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** Autogenerated timestamp when post has been created */
  @Column('timestamptz')
  @CreateDateColumn()
  created!: Date;

  /** Autogenerated timestamp when post has updated */
  @Column('timestamptz')
  @UpdateDateColumn()
  updated!: Date;

  /** Post's content */
  @Column({ nullable: false })
  @Length(1, 1000, {
    message: 'Message length can be max 1000 characters long'
  })
  message!: string;

  /** Up and down votes on post */
  @Column({ type: 'integer', default: 0 })
  votes!: number;

  /** Topic where post belongs to */
  @ManyToOne(() => Topic, (topic) => topic.posts, { onDelete: 'CASCADE' })
  topic!: Topic;

  /** User who has written post */
  @ManyToOne(() => User, (user) => user.posts)
  user!: User;
}
