/** TypeORM */
import { Entity } from 'typeorm';
import {
  Column,
  CreateDateColumn,
  OneToMany,
  PrimaryGeneratedColumn
} from 'typeorm';

/** Entities */
import { Post } from './Post';
import { Topic } from './Topic';

/** Class validation */
import { Length } from 'class-validator';

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** Autogenerated timestamp when user is created */
  @CreateDateColumn()
  created!: Date;

  /** User's username */
  @Column({ unique: true })
  @Length(3, 20, {
    message: 'Username length must be 3 - 20'
  })
  username!: string;

  /** Salted and hashed password */
  @Column()
  @Length(6, 50, {
    message: 'Password length must be at least 6 characters'
  })
  password!: string;

  /** Posts user has created */
  @OneToMany(() => Post, (post) => post.user, { onDelete: 'NO ACTION' })
  posts!: Post[];

  /** Topics user has created */
  @OneToMany(() => Topic, (topic) => topic.user, { onDelete: 'NO ACTION' })
  topics!: Topic[];
}
