/** TypeORM */
import { Entity } from 'typeorm';
import {
  Column,
  CreateDateColumn,
  OneToMany,
  PrimaryGeneratedColumn
} from 'typeorm';

/** Entities */
import { Post } from './Post';
import { Topic } from './Topic';

/** Class validation */
import { Length } from 'class-validator';

@Entity()
export class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /** Autogenerated timestamp when user is created */
  @Column('timestamptz')
  @CreateDateColumn()
  created!: Date;

  /** User's username */
  @Column({ unique: true, nullable: false })
  @Length(3, 20, {
    message: 'Username length must be 3 - 20'
  })
  username!: string;

  /** Salted and hashed password */
  @Column({ nullable: false })
  passwordHash!: string;

  /** Posts user has created */
  @OneToMany(() => Post, (post) => post.user, { onDelete: 'NO ACTION' })
  posts!: Post[];

  /** Topics user has created */
  @OneToMany(() => Topic, (topic) => topic.user, { onDelete: 'NO ACTION' })
  topics!: Topic[];
}
